tg-can-441
the-canonizer/canonizer-3.0-api pull request #101
Opened 2022-05-03 11:43 UTC by nalwa

This PR include API for can-441- "Add delegation support".

@akuks  please review and merge the PR.

2022-05-04 04:51 UTC, akuks requested changes

2022-05-04 04:51 UTC, akuks commented on app/Http/Controllers/SupportController.php
>  use App\Models\Topic;
We can remove `AddNickNameRequest` and `UpdateNickNameRequest` from the Imports.

2022-05-04 04:51 UTC, akuks commented on app/Http/Controllers/SupportController.php
> +        $userId = $user->id;
I think it is not used

2022-05-09 07:00 UTC, nalwa commented
@akuks  i have updated the change requested and resolved conflict. can you please merge PR

2022-05-09 07:02 UTC, akuks approved these changes

2022-05-09 07:02 UTC, merged