tg-can-693
the-canonizer/canonizer-3.0-api pull request #160
Opened 2022-06-13 14:09 UTC by nalwa

This PR has implementation for API can-693 and can-694

@akuks  please review and merge PR.

2022-06-13 23:10 UTC, akuks requested changes

2022-06-13 23:10 UTC, akuks commented on app/Helpers/TopicSupport.php
> +        if ($delegatedSupport->count() > 0) {
I think we can simple leave it to `if ($delegatedSupport->count() )`

2022-06-13 23:10 UTC, akuks commented on app/Helpers/TopicSupport.php
> +                $returnData['warning'] =  "You can not submit your support to this camp as its not live yet.";
May be from a common message file

2022-06-13 23:10 UTC, akuks commented on app/Helpers/TopicSupport.php
> +        if(!empty($parentSupport)){
Can we refactor this? There is too much nested if else.

2022-06-13 23:10 UTC, akuks commented on app/Models/Camp.php
> +        if (count($mysupports))
probably a ternary operator will reduce the complexity

2022-06-20 13:56 UTC, nalwa commented
@akuks  I have done changes requested and suggested by you. please review once again.

2022-06-20 21:44 UTC, akuks approved these changes

2022-06-20 21:44 UTC, merged