Can-885
the-canonizer/canonizer-3.0-api pull request #203
Opened 2022-07-15 11:16 UTC by M-Darab

statement related emails through queue jobs

2022-07-18 02:53 UTC, akuks requested changes

2022-07-18 02:53 UTC, akuks commented on app/Http/Controllers/StatementController.php
> +            if ($eventType == "create" && $statement->grace_period == 0) {
I think we need to refactor this

2022-07-19 05:48 UTC, M-Darab commented on app/Http/Controllers/StatementController.php
> +            if ($eventType == "create" && $statement->grace_period == 0) {
yes i refactored it

2022-07-19 10:22 UTC, akuks approved these changes

2022-07-21 09:03 UTC, akuks approved these changes

2022-07-21 09:03 UTC, merged