Can 922
the-canonizer/canonizer-3.0-api pull request #208
Opened 2022-07-19 14:02 UTC by M-Darab

Api for camp history

2022-07-20 08:33 UTC, akuks requested changes

2022-07-20 08:33 UTC, akuks commented on app/Models/Support.php
> +            $support = self::where('topic_num','=',$filter['topicNum'])->whereIn('camp_num',$allChildCamps)->whereIn('nick_name_id',$nickNames)->where('delegate_nick_name_id',0)->where('end','=',0)->
How about this
```php
$support = self::where('topic_num','=',$filter['topicNum'])->whereIn('camp_num',$allChildCamps)->whereIn('nick_name_id',$nickNames)->where('delegate_nick_name_id',0)->where('end','=',0)
->where(function($query) use ($submit_time)
{
    if ($submit_time) {
        $query->where('start','<=',$submit_time);
    }
})->first()

```

2022-07-20 08:33 UTC, akuks commented on app/Models/Support.php
> +            $support = self::where('topic_num','=',$filter['topicNum'])->whereIn('camp_num',$allChildCamps)->whereIn('nick_name_id',$nickNames)->where('delegate_nick_name_id',0)->where('end','=',0)->
Can you please test it

2022-07-20 11:01 UTC, M-Darab commented on app/Models/Support.php
> +            $support = self::where('topic_num','=',$filter['topicNum'])->whereIn('camp_num',$allChildCamps)->whereIn('nick_name_id',$nickNames)->where('delegate_nick_name_id',0)->where('end','=',0)->
Yes its working perfect. Thanks

2022-07-25 04:14 UTC, akuks approved these changes

2022-07-25 04:14 UTC, akuks commented
@M-Darab Can you plese resolve the conflicts?

2022-07-26 10:45 UTC, merged