can-1277
the-canonizer/canonizer-3.0-api pull request #316
Opened 2022-10-07 07:54 UTC by shahab-ramzan

first letter capital in activity logs

2022-10-10 05:48 UTC, akuks requested changes

2022-10-10 05:48 UTC, akuks commented on app/Helpers/TopicSupport.php
> +            $activity = "Support removed";
Please move it to common message file

2022-10-10 05:48 UTC, akuks commented on app/Helpers/TopicSupport.php
>              $description = "supoort removed";
Please move it to common message file

2022-10-10 05:48 UTC, akuks commented on app/Helpers/TopicSupport.php
> +            $activity = "Support added";
Please move it to common message file

2022-10-10 05:48 UTC, akuks commented on app/Helpers/TopicSupport.php
>              $description = "supoort added";
Please move it to common message file

2022-10-10 05:48 UTC, akuks commented on app/Helpers/TopicSupport.php
>              $description = "supoort removed";
There is also a typo

2022-10-14 07:35 UTC, akuks requested changes

2022-10-14 07:35 UTC, akuks commented on resources/lang/en/message.php
> +        'support_added' => "Support added.",
Same for this

2022-10-14 12:30 UTC, sajid315 commented on resources/lang/en/message.php
> +        'support_added' => "Support added.",
Same for this means ? Messages are moved to language file where all other exists.

2022-10-17 10:32 UTC, akuks approved these changes

2022-10-17 10:32 UTC, merged