tg-can-1183
the-canonizer/canonizer-3.0-api pull request #320
Opened 2022-10-11 11:22 UTC by nalwa

This PR has fixes for can-1183, can-1184, can-1188

@akuks  please review and merge PR

2022-10-12 04:15 UTC, akuks requested changes

2022-10-12 04:15 UTC, akuks commented on app/Helpers/Util.php
> +                    if (sizeof($supporterNicknames) > 0)
`{` should be inline with others if and foreach statement

2022-10-12 11:53 UTC, nalwa commented on app/Helpers/Util.php
> +                    if (sizeof($supporterNicknames) > 0)
done

2022-10-12 14:17 UTC, akuks requested changes
@nalwa Please do the required changes

2022-10-12 14:17 UTC, akuks commented on app/Helpers/Util.php
> +                if (sizeof($supporterNicknames) > 0)
Please align `if(){` as in the line 396. Similar foreach in the below statements

2022-10-12 14:17 UTC, akuks commented on app/Helpers/Util.php
> +               /* if (sizeof($supporterNicknames) > 0) {
Remove this if not required

2022-10-13 02:32 UTC, akuks approved these changes

2022-10-13 02:32 UTC, merged