Iffort fixed backlog issue
the-canonizer/canonizer-3.0-api pull request #327
Opened 2022-10-12 12:14 UTC by ashish76

2022-10-13 02:33 UTC, akuks requested changes
Please do the request changes

2022-10-13 02:33 UTC, akuks commented on app/Http/Controllers/ThreadsController.php
> +                if($threads->title !== Util::remove_emoji($request->title)){
I think there is an extra "=" in the comparison

2022-10-13 04:52 UTC, ashish76 commented on app/Http/Controllers/ThreadsController.php
> +                if($threads->title !== Util::remove_emoji($request->title)){
!= fails when we are compressing a string to an integer, so we are using !==
And the issue is resolved if we are using !==

2022-10-14 07:36 UTC, akuks approved these changes

2022-10-14 07:36 UTC, merged