CAN - 111
the-canonizer/canonizer-3.0-api pull request #58
Opened 2022-03-25 13:46 UTC by ashish76

1. CAN - 326 Create API for social list
2. CAN - 327 Create link and unlink API

2022-03-28 10:47 UTC, akuks requested changes

2022-03-28 10:47 UTC, akuks commented on app/Http/Controllers/UserController.php
> +                    $socialUser = SocialUser::create([
This is not seems to be used any where

2022-03-28 10:47 UTC, akuks commented on app/Http/Controllers/UserController.php
> +                    $socialUser = SocialUser::create([
Social::Create command is repeated

2022-03-28 10:47 UTC, akuks commented on app/Http/Controllers/UserController.php
> +            if($request->user()){
Can you please move multiple if else in a separate function or may be further break it down. As it is not very readable.

2022-03-29 11:35 UTC, akuks requested changes
Please go through the changes

2022-03-29 11:35 UTC, akuks commented on app/Http/Controllers/UserController.php
> +                if($generateToken->status_code == 200){
Code from 1109-1119 is same as 464-474

2022-03-29 11:35 UTC, akuks commented on app/Http/Controllers/UserController.php
> +    public function SocialLink(Request $request, Validate $validate)
Functioname should be in camelcase

2022-03-29 11:35 UTC, akuks commented on app/Http/Controllers/UserController.php
> +    public function SocialDelete(Request $request, $id)
Functioname should be in camelcase

2022-03-29 11:35 UTC, akuks commented on app/Http/Controllers/UserController.php
> +    protected function CreateSocialUser($data,$provider,$userId)
Functioname should be in camelcase

2022-03-30 05:17 UTC, ashish76 commented on app/Http/Controllers/UserController.php
> +    protected function CreateSocialUser($data,$provider,$userId)
Done

2022-03-30 05:17 UTC, ashish76 commented on app/Http/Controllers/UserController.php
> +    public function SocialDelete(Request $request, $id)
Done

2022-03-30 05:17 UTC, ashish76 commented on app/Http/Controllers/UserController.php
> +    public function SocialLink(Request $request, Validate $validate)
Done

2022-03-30 05:17 UTC, ashish76 commented on app/Http/Controllers/UserController.php
> +                if($generateToken->status_code == 200){
Done

2022-03-30 06:02 UTC, merged