tg-upload-apis
the-canonizer/canonizer-3.0-api pull request #73
Opened 2022-04-06 13:31 UTC by nalwa

This PR includes API for :

2022-04-07 04:26 UTC, akuks requested changes

2022-04-07 04:26 UTC, akuks commented on app/Http/Controllers/UploadController.php
> +use Illuminate\Support\Facades\Storage;
If not used, we can delete this

2022-04-07 04:26 UTC, akuks commented on app/Http/Controllers/UploadController.php
> +                    'Bucket' => 'canonizer-public-file',
this should also comes from the env file

2022-04-07 04:26 UTC, akuks commented on app/Http/Controllers/UploadController.php
> +        $input = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
Should be in config or env file

2022-04-07 04:26 UTC, akuks commented on app/Http/Controllers/UploadController.php
> +                return $this->resProvider->apiJsonResponse($status, $message, null, null);
`return` statment should be moved out of if else

2022-04-12 09:41 UTC, nalwa commented
@akuks  change requested are fixed. Please review and merge PR.

2022-04-12 10:07 UTC, merged